# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-20 22:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GithubUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('firstname', models.CharField(blank=True, max_length=64)),
                ('lastname', models.CharField(blank=True, max_length=64)),
                ('github', models.CharField(blank=True, max_length=48, unique=True)),
                ('github_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('github_token', models.CharField(blank=True, max_length=256)),
                ('avatar_url', models.CharField(blank=True, max_length=256)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('number', models.PositiveIntegerField(unique=True)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Assignment',
            },
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pull_request', models.URLField(blank=True, null=True, unique=True)),
                ('merged', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Submission',
            },
        ),
        migrations.CreateModel(
            name='AssignmentTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, default='')),
                ('number', models.PositiveIntegerField(default=1)),
                ('points', models.PositiveSmallIntegerField(default=1)),
                ('flags', models.TextField(blank=True, max_length=1024)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='classroom.Assignment')),
            ],
            options={
                'verbose_name': 'Task',
            },
        ),
        migrations.CreateModel(
            name='AssignmentTestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_input', models.TextField(blank=True, max_length=8096)),
                ('case_output', models.TextField(blank=True, max_length=8096)),
                ('tasks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testcases', to='classroom.AssignmentTask')),
            ],
            options={
                'verbose_name': 'Task Testcase',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_class', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('V', 'V'), ('G', 'G')], max_length=1, null=True)),
                ('student_grade', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('student_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.Student'),
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together=set([('student_grade', 'student_class', 'student_number')]),
        ),
        migrations.AlterUniqueTogether(
            name='assignmenttask',
            unique_together=set([('assignment', 'number')]),
        ),
    ]
