# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 12:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=48)),
                ('description', models.TextField()),
                ('assignment_type', models.CharField(choices=[('H', 'Homework'), ('E', 'Exam'), ('P', 'Practice')], default='H', max_length=1)),
                ('start', models.DateTimeField(default=django.utils.timezone.now)),
                ('end', models.DateTimeField()),
                ('target', models.CharField(choices=[('A', 'A class'), ('B', 'B class'), ('V', 'V class'), ('G', 'G class'), ('ALL', 'ALL classes')], default='ALL', max_length=3)),
                ('code', models.CharField(default=uuid.uuid4, editable=False, max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Assignment',
            },
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pull_request', models.URLField(blank=True, null=True)),
                ('grade', models.PositiveSmallIntegerField(default=0)),
                ('description', models.CharField(blank=True, max_length=256)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='classroom.Assignment')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Student')),
            ],
            options={
                'verbose_name': 'Submission',
            },
        ),
        migrations.CreateModel(
            name='AssignmentTestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.PositiveIntegerField(default=1)),
                ('case_input', models.TextField(blank=True, max_length=8096)),
                ('case_output', models.TextField(blank=True, max_length=8096)),
                ('flags', models.TextField(blank=True, max_length=1024)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testcases', to='classroom.Assignment')),
            ],
            options={
                'verbose_name': 'Assignment test case',
            },
        ),
        migrations.CreateModel(
            name='SubmissionReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('points', models.PositiveSmallIntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='classroom.AssignmentSubmission')),
            ],
            options={
                'verbose_name': 'Review',
            },
        ),
        migrations.AlterUniqueTogether(
            name='assignmentsubmission',
            unique_together=set([('assignment', 'pull_request')]),
        ),
    ]
