# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-20 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmenttestcase',
            name='flags',
        ),
        migrations.AddField(
            model_name='assignmenttask',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='assignmenttask',
            name='flags',
            field=models.TextField(blank=True, max_length=1024),
        ),
    ]
